kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  # these labels are deployment related labels
  labels:
    componet: backend
    project: expense
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: backend
      tier: app
      project: expense
  # pod definition
  template:
    metadata:
      labels:
        component: backend
        tier: app
        project: expense
    spec:
      containers:
      - name: backend
        image: joindevops/backend:{{ .Values.deployment.imageversion }}
        envFrom:
        - configMapRef:
            name: backend
            