apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    tier: app
    project: expense
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port